[project]
name = "demo"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.2.1",
    "langchain>=1.2.0",
    "langgraph>=1.0.5",
    "langchain-openai>=1.1.6",
    "langchain-anthropic>=1.3.0",
]
